
title: Overthinking
email_username: bbuluttekin@gmail.com
header-img: img/main.jpeg
author: "Baran Buluttekin"
description: "Data science & software"
copyright_name: "Baran Buluttekin"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://verybigdata.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BuluttekinBaran
github_username:  bbuluttekin
linkedin_username: bbuluttekin
google_tracking_id: G-MGDCDDD6KX
paginate: 5

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
permalink: /:title
theme: minima
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - AGENTS.md
  - plans

timezone: Europe/London
#Defult settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: "Baran Buluttekin"
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      author: "Baran Buluttekin"
      layout: "page"
