
title: Overthinking
email_username: bbuluttekin@gmail.com
header-img: img/main.jpeg
author: "Baran Buluttekin"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BuluttekinBaran
github_username:  bbuluttekin
linkedin_username: bbuluttekin
google_tracking_id: UA-98650425-1
paginate: 5

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
permalink: /:title
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

#Defult settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: Baran Buluttekin
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      author: Baran
      layout: "page"
